---
name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read

jobs:
  
  ProvidersAndExtensions:
    runs-on: windows-latest
    

    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    # Run powershell script to create VM
    - name: RunPowershellScriptFromRepo
      env: #Set secrets as environment variables
        ARC_SP_CLIENT_ID: ${{ secrets.ARC_SP_CLIENT_ID }}
        ARC_SP_CLIENT_SECRET: ${{ secrets.ARC_SP_CLIENT_SECRET }}
        ARC_SP_TENANT_ID: ${{ secrets.ARC_SP_TENANT_ID }}
        ARC_AZURE_SUBSCRIPTION_ID: ${{ secrets.ARC_AZURE_SUBSCRIPTION_ID }}
      run: .\providersandextensions.ps1
      shell: pwsh
