name: Azure Arc Workflow


on:
  push:
    branches:
      - main
  pull_request: null


permissions:
  contents: read


jobs:

  variables:
    - template: .\pipeline.variables.yml 
    

  ProvidersAndExtensions:
    runs-on: windows-latest
    
    

    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1


    # Run script
    - name: RunScriptFromRepo
      env: #Set secrets as environment variables
        ARC_SP_CLIENT_ID: ${{ secrets.ARC_SP_CLIENT_ID }}
        ARC_SP_CLIENT_SECRET: ${{ secrets.ARC_SP_CLIENT_SECRET }}
        ARC_SP_TENANT_ID: ${{ secrets.ARC_SP_TENANT_ID }}
        ARC_AZURE_SUBSCRIPTION_ID: ${{ secrets.ARC_AZURE_SUBSCRIPTION_ID }}
        resourceGroup: $(resourceGroup)
        dataControllername: $(dataControllername)
        adConnectorname: $(adConnectorname)
        sqlManagedInstanceName: $(sqlManagedInstanceName)
        sqlAccountName: $(sqlAccountName)
        PortNumber: $(PortNumber)
        CustomLocationName: $(CustomLocationName)
        AZDATA_USERNAME: $(AZDATA_USERNAME)
        AZDATA_PASSWORD: $(AZDATA_PASSWORD)
        ACCEPT_EULA: $(ACCEPT_EULA)
        location: $(location)
      run: .\providersandextensions.ps1
      shell: pwsh