name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read

jobs:
  
  ProvidersAndExtensions:
    runs-on: windows-latest
    

    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    # Read the parameters file
    - name: RunScriptToReadParameters
      run: |
        .\readParameters.ps1 
        echo ::set-output name=resourceGroup::$($resourceGroup)
      shell: pwsh


   