name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read

jobs:
  
  ProvidersAndExtensions:
    runs-on: windows-latest
    

    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    
    # Read the parameters file
    - name: newSetVarFromJsonFileValue
      id: step_one
      env:
          COMMIT_VAR: ${{ contains(github.event.head_commit.message, '[commit var]') }}
      run: |
        $myjsonfile = Import-PowerShellDataFile -Path .\newglobalparameters.json
        echo $myjsonfile
        echo $myjsonfile.PortNumber     
        echo "resourceGroupName=$($myjsonfile.resourceGroupName)" >> $GITHUB_ENV  
        echo "flag set to true"
      shell: pwsh

    # Read the parameters file
    - name: setVarFromJsonFileValue
      id: step_two
      run: |
       echo "##vso[task.setvariable variable=resourceGroupName;]$(jq .resourceGroupName globalparameters.json)" 
       echo "my resourceGroupName: "
       echo ${{ env.resourceGroupName }}
      shell: bash
