name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  
  ProvidersAndExtensions:
    runs-on: windows-latest
    

    steps:
      
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    
    # Read the parameters file
    - name: newSetVarFromJsonFileValue
      id: step_one
      run: |
        $myjsonfile = Import-PowerShellDataFile -Path .\newglobalparameters.json
        echo $myjsonfile
        echo "my port number: " $myjsonfile.PortNumber   
        echo "resourceGroupName2=$($myjsonfile.resourceGroupName)" >> $GITHUB_ENV
        echo "::set-env name=resourceGroupName1::$($myjsonfile.resourceGroupName)"
      shell: pwsh
      env:
        resourceGroupName2: $($myjsonfile.resourceGroupName)

    # Read the parameters file
    - name: setVarFromJsonFileValue
      id: step_two
      run: |
       echo "##vso[task.setvariable variable=resourceGroupName;]$(jq .resourceGroupName globalparameters.json)" 
       echo "my resourceGroupName: "
       echo ${{env.resourceGroupName2}}
       echo ${{env.resourceGroupName1}}
      shell: pwsh