name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  
  ProvidersAndExtensions:
    if: ${{ !contains(github.event.head_commit.message, 'vivek') }}
    runs-on: windows-latest
    

    steps:
      
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    
    # Read the parameters file
    - name: newSetVarFromJsonFileValue
      id: step_one
      run: |
        $myjsonfile = Import-PowerShellDataFile -Path .\dev-parameters.json
        echo $myjsonfile
        echo $myjsonfile.PortNumber   
        echo "::set-env name=RESOURCEGROUPNAME::$($myjsonfile.RESOURCEGROUPNAME)"
        echo "::set-env name=DATACONTROLLERNAME::$($myjsonfile.DATACONTROLLERNAME)"
        echo "::set-env name=CLUSTEREXISTS::$($myjsonfile.CLUSTEREXISTS)"
        echo "::set-env name=LOCATION::$($myjsonfile.LOCATION)"
        echo "::set-env name=CLUSTERNAME::$($myjsonfile.CLUSTERNAME)"
        echo "::set-env name=CLNAME::$($myjsonfile.CLNAME)"      
        echo "::set-env name=NAMESPACE::$($myjsonfile.NAMESPACE)"
        echo "::set-env name=CONNECTIVITYMODE::$($myjsonfile.CONNECTIVITYMODE)"
        echo "::set-env name=AUTOUPLOADMETRICS::$($myjsonfile.AUTOUPLOADMETRICS)"
        echo "::set-env name=AUTOUPLOADLOGS::$($myjsonfile.AUTOUPLOADLOGS)"
        echo "::set-env name=PROFILENAME::$($myjsonfile.PROFILENAME)"
        echo "::set-env name=STORAGECLASS::$($myjsonfile.STORAGECLASS)"
        echo "::set-env name=ADSEXTENSIONNAME::$($myjsonfile.ADSEXTENSIONNAME)"
        echo "::set-env name=SPNID::$($myjsonfile.SPNID)"
        echo "::set-env name=AZURE_SUBSCRIPTION_ID::$($myjsonfile.AZURE_SUBSCRIPTION_ID)"
        
        
      shell: pwsh
      

    # Read the parameters file
    - name: setVarFromJsonFileValue
      id: step_two
      run: |
       echo "my resourceGroupName: "
       echo ${{env.RESOURCEGROUPNAME}}       
       echo ${{env.DATACONTROLLERNAME}}
       echo ${{env.CLUSTEREXISTS}}
       echo ${{env.LOCATION}}
       echo ${{env.CLUSTERNAME}}
       echo ${{env.CLNAME}}
       echo ${{env.NAMESPACE}}
       echo ${{env.CONNECTIVITYMODE}}
       echo ${{env.AUTOUPLOADMETRICS}}
       echo ${{env.AUTOUPLOADLOGS}}
       echo ${{env.PROFILENAME}}
       echo ${{env.STORAGECLASS}}
       echo ${{env.ADSEXTENSIONNAME}}
       echo ${{env.SPNID}}
       echo ${{env.AZURE_SUBSCRIPTION_ID}}
      shell: pwsh

    - name: RunScriptFromRepo
      env: #Set secrets as environment variables
        ARC_SP_CLIENT_ID: ${{ secrets.ARC_SP_CLIENT_ID }}
        ARC_SP_CLIENT_SECRET: ${{ secrets.ARC_SP_CLIENT_SECRET }}
        ARC_SP_TENANT_ID: ${{ secrets.ARC_SP_TENANT_ID }}
        AZDATA_USERNAME: ${{ secrets.AZDATA_USERNAME }}
        AZDATA_PASSWORD: ${{ secrets.AZDATA_PASSWORD }}
      run: .\providersandextensions.ps1
      shell: pwsh