name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read

jobs:
  
  ProvidersAndExtensions:
    runs-on: windows-latest
    

    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    # Read the parameters file
    - name: setVarFromJsonFileValue
      run: |
       echo "##vso[task.setvariable variable=resourceGroupName;]$(jq .resourceGroupName globalparameters.json)"
      shell: bash

    - name: printValueFromJsonFileValue
      run: |
       echo "resourceGroupName :"  $(resourceGroupName)
      shell: bash


    - name: newWayReadingFromJsonFileValue
      run: |
        echo "PACKAGE_JSON=$(jq -c . < globalparameters.json)" >> $GITHUB_ENV
        echo ${{ fromJson(env.PACKAGE_JSON).resourceGroupName }}
        echo ${{ fromJson(env.PACKAGE_JSON).dataControllername }}
