name: Azure Arc Workflow
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read
env:
  resourceGroupName: xyz

jobs:
  
  ProvidersAndExtensions:
    runs-on: windows-latest
    

    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    
    # Read the parameters file
    - name: newSetVarFromJsonFileValue
      id: step_one
      run: |
        $myjsonfile = Import-PowerShellDataFile -Path .\newglobalparameters.json
        echo $myjsonfile
        echo $myjsonfile.PortNumber     
        echo "resourceGroupName=$($myjsonfile.resourceGroupName)" >> $GITHUB_ENV  
        echo "flag set to true"
      env:
        resourceGroupName1: $myjsonfile.PortNumber 
      shell: pwsh

    # Read the parameters file
    - name: setVarFromJsonFileValue
      id: step_two
      run: |
       echo "##vso[task.setvariable variable=resourceGroupName;]$(jq .resourceGroupName globalparameters.json)" 
       echo "my resourceGroupName: "
       echo ${{ env.resourceGroupName }}
       echo ${{ env.resourceGroupName1 }}
      shell: pwsh
